### ISSUE TITLE
LOGO ?!?!?

### ISSUE THREAD

**Issue by trottomv** [andreaangeloni/angeloni.github.io#6]

**Comment by mandyellow** [comment]
Hello! I made a logo for your project. Let me know if you like it so I can open a PR with the PNG and an SVG (or another image format) to you. 🦊

Icon and logo (primary and negative logo):

![image](https://user-images.githubusercontent.com/30158643/94974450-01412300-04e5-11eb-95d8-08f92c603698.png)
